apiVersion: aws.platform.io/v1alpha1
kind: VPC
metadata:
  name: main
spec:
  region: us-west-2
  providerConfigRef:
    name: PLACEHOLDER # Will be patched by kustomize
  cidrBlock: "10.0.0.0/16" # Will be patched by kustomize
  enableDnsSupport: true
  enableDnsHostnames: true
  tags:
    ManagedBy: crossplane
    Purpose: eks-clusters