apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: accounts
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/accounts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane
    - name: cluster-api
  wait: true
  timeout: 5m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: aws-accounts-registry
        optional: true