apiVersion: v1
kind: ConfigMap
metadata:
  name: account-info
data:
  ACCOUNT_ID: "137457118074"
  ACCOUNT_NAME: "Test Account 1"
  ACCOUNT_ALIAS: "test-account-1"
  ENVIRONMENT: "development"
  NAMESPACE: "aws-test-account-1"
  REGION: "us-west-2"