apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: control-plane-kubeadm
  namespace: cluster-api-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/cluster-api
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: control-plane-kubeadm
  namespace: cluster-api-system
spec:
  interval: 15m
  chart:
    spec:
      chart: control-plane-provider-kubeadm
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: control-plane-kubeadm
        namespace: cluster-api-system
  values:
    manager:
      featureGates:
        ClusterTopology: true
